/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as MesaIdRouteImport } from './routes/mesa.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaIdRoute = MesaIdRouteImport.update({
  id: '/mesa/$id',
  path: '/mesa/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nueva': typeof NuevaRoute
  '/mesa/$id': typeof MesaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nueva': typeof NuevaRoute
  '/mesa/$id': typeof MesaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nueva': typeof NuevaRoute
  '/mesa/$id': typeof MesaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nueva' | '/mesa/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nueva' | '/mesa/$id'
  id: '__root__' | '/' | '/nueva' | '/mesa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NuevaRoute: typeof NuevaRoute
  MesaIdRoute: typeof MesaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$id': {
      id: '/mesa/$id'
      path: '/mesa/$id'
      fullPath: '/mesa/$id'
      preLoaderRoute: typeof MesaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NuevaRoute: NuevaRoute,
  MesaIdRoute: MesaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
